/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "You can view the Source Code on": "您可以在以下位置查看源代码",
    "Go on an Adventure with at least one bonus": "带着至少一个奖励去冒险",
    "Goblet of Energy": "能量杯",
    "Goblet of Fire": "火焰杯",
    "Goblet of Mystics": "神秘酒杯",
    "Gold axe": "金斧",
    "Gold ore": "金矿",
    "Gold Pickaxe": "金镐",
    "Gold Scythe": "金镰刀",
    "Gold Sword": "金剑",
    "Gold Tier Pack": "黄金等级包",
    "Grain": "粮食",
    "Have your wood resources burned down": "烧毁你的木材资源",
    "Heal 10 hitpoints": "治疗 10 点生命值",
    "Here you can view your collected Cards. Build your Decks and save them using the Deck Presets.": "在这里您可以查看您收集的卡片。构建您的套牌并使用套牌预设保存它们。",
    "How to play": "怎么玩",
    "I realize it isn't the most traditional incremental game, but it should still be enjoyable :)": "我意识到这不是最传统的增量游戏，但它应该仍然很有趣:)",
    "If you've done impressive things, they will show up here.": "如果你做了令人印象深刻的事情，它们就会出现在这里。",
    "Import Level": "进口级别",
    "In this game you don't play against another player, or an AI. You play against the Level.": "在这个游戏中，您不会与其他玩家或 AI 对战。你和关卡对战。",
    "Incremental Game Template": "增量游戏模板",
    "Introduction": "介绍",
    "Isha": "伊莎",
    "It uses the": "它使用",
    "jam of 2021.": "2021年的果酱。",
    "Land Mine": "地雷",
    "Legendary Pack": "传奇包",
    "Level Editor": "关卡编辑器",
    "Load": "加载",
    "Log": "日志",
    "Made from the bronzest bronze.\nReplaces current weapon": "由青铜制成。\n替换当前武器",
    "Magic touch": "神奇的触摸",
    "Master Farmer": "农夫大师",
    "Monster Pack": "怪物包",
    "Monsters": "怪物",
    "More difficult Levels award rarer and better Cards.": "更难的关卡奖励更稀有和更好的卡片。",
    "Mystic Strike": "神秘打击",
    "Mystic Surge": "神秘涌动",
    "New Deck": "新甲板",
    "None": "没有任何",
    "Pig": "猪",
    "Play 100 Action cards": "玩 100 张行动卡",
    "Play 100 Monster cards": "打出 100 张怪物卡",
    "Play 100 Resource cards": "玩 100 张资源卡",
    "Play 100 Tool cards": "玩 100 张工具卡",
    "Play custom level": "玩自定义关卡",
    "Play the Frozen 2 Blast card": "玩冰雪奇缘 2 爆破卡",
    "Play the Goblet of Fire card": "玩火焰杯卡",
    "Possible Rewards": "可能的奖励",
    "Preview the Adventure before taking it on to see which cards will be played.": "在开始冒险之前先预览一下，看看会打出哪些牌。",
    "Q to instantly forfeit": "Q立即放弃",
    "Quick tips": "快速提示",
    "r/incremental_games": "r/incremental_games",
    "Rat": "鼠",
    "Reset save": "重置保存",
    "Reset to default": "重置为默认",
    "Resources": "资源",
    "Rod of Asclepius": "阿斯克勒庇俄斯之杖",
    "Sacrifice hand": "牺牲之手",
    "Shift + 1-9 to Discard Cards": "Shift + 1-9 丢弃卡片",
    "Shift + Click Cards to discard them": "Shift + 单击卡片以丢弃它们",
    "Show save message": "显示保存信息",
    "Show unobtained cards": "显示未获得的卡片",
    "Silver axe": "银斧",
    "Silver ore": "银矿石",
    "Silver Pickaxe": "银镐",
    "Silver Scythe": "银镰",
    "Silver Sword": "银剑",
    "Silver Tier Pack": "银色层包",
    "Skeleton": "骨骼",
    "Skeleton King": "骷髅王",
    "Spend your money on starting bonuses": "把钱花在开始奖金上",
    "Spend your money on starting stats to skip the early game (if you can afford it).": "把钱花在开始统计数据上以跳过早期游戏（如果你负担得起的话）。",
    "Spider": "蜘蛛",
    "Spiderling": "小蜘蛛",
    "Starting stats": "开始统计",
    "Stone Axe": "石斧",
    "Stone Pick": "石镐",
    "Stone Scythe": "石镰",
    "Straw": "稻草",
    "Take your Deck and go on an Adventure.": "带上你的甲板去冒险。",
    "Tap every card in the field once": "点按该区域中的每张卡片一次",
    "Thank you for playing, I hope you liked it.": "谢谢你玩，希望你喜欢。",
    "The Cellar": "地窖",
    "The Level plays cards at certain turns. These cards are known beforehand so you can build your deck around it.": "关卡在某些回合打牌。这些卡是事先已知的，因此您可以围绕它构建您的套牌。",
    "The Level will Play certain Cards at certain turns": "关卡会在特定回合打出特定卡牌",
    "The max amount of a single card is 10. You need at least 15 cards in your deck to start a level.": "单张卡片的最大数量为 10。您的牌组中至少需要 15 张卡片才能开始一个关卡。",
    "This game was Developed in 7 days by": "这个游戏是在7天内开发的",
    "Tools": "工具",
    "Tree": "树",
    "Troll": "巨魔",
    "Turn": "转动",
    "Use a curse on yourself": "对自己使用诅咒",
    "Viking Shield": "维京盾牌",
    "W to Wait a turn": "W 等待转弯",
    "When the counter reaches 0, it attacks.\nGain 1 souls on defeat": "当计数器达到 0 时，它会攻击。\n击败时获得 1 个灵魂",
    "When you complete a Level, you gain some Cards to further improve your deck!": "当你完成一个关卡时，你会获得一些卡片来进一步提升你的套牌！",
    "Whenever you perform an Action, the turn increases.": "每当你执行一个动作时，回合就会增加。",
    "You can Play a card, to place it on the Field.": "您可以打出一张牌，将其放在场上。",
    "You can share your Decks with other players by importing and exporting their codes!": "您可以通过导入和导出代码与其他玩家分享您的套牌！",
    "You can use these Resources to upgrade your Tools and Weapons, or Play Action cards!": "您可以使用这些资源来升级您的工具和武器，或玩行动卡！",
    "1-9 to Play Cards": "1-9 出牌",
    "A bit stronger.\nReplaces current weapon": "更强一点。\n替换当前武器",
    "A good place to start": "一个很好的起点",
    "Action Card Pack": "行动卡包",
    "Actions": "行动",
    "Adventure": "冒险",
    "All": "全部",
    "Artwork taken from": "作品取自",
    "Automation": "自动化",
    "Basic Sword": "基础剑",
    "Battle your way through different Levels and defeat your enemies!": "通过不同的关卡战斗并击败你的敌人！",
    "Beginner Pack": "初学者包",
    "Bread": "面包",
    "Bronze axe": "青铜斧",
    "Bronze ore": "青铜矿",
    "Bronze Pickaxe": "青铜镐",
    "Bronze Scythe": "青铜镰刀",
    "Bronze Sword": "青铜剑",
    "Bronze Tier Pack": "青铜等级包",
    "Card Collection": "卡片收藏",
    "Card Quest is a Card Collection Game!": "Card Quest是一款卡片收集游戏！",
    "Cards can have costs to Play them, or Resources when they leave the Field (or both).": "卡牌在离开场地时可能会产生费用或资源（或两者兼有）。",
    "Cards in the Field can be Tapped to interact with them.": "可以点击场中的卡片与它们互动。",
    "Check the settings for things you want to toggle.": "检查您要切换的内容的设置。",
    "Chicken": "鸡",
    "Cluck cluck.\nGain 1 souls on defeat": "咯咯咯。\n击败时获得 1 个灵魂",
    "Collect Cards, build your Deck, and go on Adventures!": "收集卡片，建立你的牌组，然后继续冒险！",
    "Complete the Dragons Den": "完成巨龙巢穴",
    "Complete the first level": "完成第一关",
    "Complete the The Farm level": "完成农场关卡",
    "Complete the The Necromancer level": "完成死灵法师关卡",
    "Complete the The Spiders Den": "完成蜘蛛巢穴",
    "Complete the The Troll level": "完成巨魔关卡",
    "Complete the The Wizard level": "完成巫师关卡",
    "Cow": "奶牛",
    "Cracked Shield": "破裂的盾牌",
    "Create custom levels to challenge your friends!": "创建自定义关卡来挑战你的朋友！",
    "Credits": "学分",
    "Ctrl + 1-9 to Tap Cards": "Ctrl + 1-9 点击卡片",
    "Curse Pack": "诅咒包",
    "Curses": "诅咒",
    "D to Draw": "D 绘图",
    "Defeat The Wizard Level to unlock automation": "击败巫师关卡以解锁自动化",
    "Discard hand": "弃手",
    "Dragon": "龙",
    "Draw 3 cards": "抽3张牌",
    "Draw 3 cards in a single turn": "一回合抽3张牌",
    "Empty current Deck": "空当前甲板",
    "Energy Strike": "能量打击",
    "Energy Surge": "能量激增",
    "Export Level": "出口水平",
    "Farm Pack": "农场包",
    "Fire Strike": "火力打击",
    "Fire Surge": "火涌",
    "First Deck (0)": "第一层 (0)",
    "for the": "为了",
    "Forest": "森林",
    "Forest Fire": "森林火灾",
    "Freeze all monsters for 5 turns": "冻结所有怪物 5 回合",
    "Frozen 2 Blast": "冰雪奇缘2爆炸",
    "Frozen Blast": "冷冻爆破",
    "Gain 1 Bronze ore when mined": "开采时获得 1 个青铜矿石",
    "Gain 1 Grain when cut down": "砍伐时获得 1 粒谷物",
    "Gain 1 Wood when cut down": "砍伐时获得 1 个木材",
    "Game saved!": "游戏已保存！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Gain (.+) money in total$/, '总共获得 $1 金钱'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\-([\d\.,]+) turns$/, '\-$1 回合'],
    [/^([\d\.,]+) Base health$/, '$1 基础生命值'],
    [/^([\d\.,]+) Starting Cards$/, '$1 初始卡牌'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);